### PR TITLE
Test unit tests

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Thanks for the feedback. After the new helper function the result of single and multi-mime type iamge:

## Multi Mime
`'image/jpeg' => array( 'image/jpeg', 'image/webp', 'image/avif' )`

<details>

<summary>Medium Size</summary>
## fdsfsg
```php
<picture class="wp-picture-43" style="display: contents;">
  <source type="image/avif" srcset="http://localhost:8888/wp-content/uploads/2024/08/car-300x169-jpeg.avif">
  <source type="image/webp" srcset="http://localhost:8888/wp-content/uploads/2024/08/car-300x169-jpeg.webp">
  <img fetchpriority="high" decoding="async" width="300" height="169" src="http://localhost:8888/wp-content/uploads/2024/08/car-300x169.jpeg" alt="" class="wp-image-43">
</picture>
```
</details>
<details>
<summary>Large Size</summary>
<picture class="wp-picture-43" style="display: contents;"><source type="image/avif" srcset="http://localhost:8888/wp-content/uploads/2024/08/car-1024x576-jpeg.avif"><source type="image/webp" srcset="http://localhost:8888/wp-content/uploads/2024/08/car-1024x576-jpeg.webp"></picture>
</details>
<details>
<summary>Full Size</summary>
<picture class="wp-picture-43" style="display: contents;"><source type="image/avif" srcset="http://localhost:8888/wp-content/uploads/2024/08/car-jpeg.avif"><source type="image/webp" srcset="http://localhost:8888/wp-content/uploads/2024/08/car-jpeg.webp"></picture>
</details>

## Single Mime
`'image/jpeg' => array( 'image/jpeg', 'image/avif)`

<details>
<summary>Medium Size</summary>
<figure class="wp-block-image size-medium"><picture class="wp-picture-46" style="display: contents;"><source type="image/avif" srcset="http://localhost:8888/wp-content/uploads/2024/08/leaves-300x200-jpg.avif"></picture></figure>
</details>
<details>
<summary>Large Size</summary>
<figure class="wp-block-image size-large"><picture class="wp-picture-46" style="display: contents;"><source type="image/avif" srcset="http://localhost:8888/wp-content/uploads/2024/08/leaves-1024x683-jpg.avif"></picture></figure>
</details>
<details>
<summary>Full Size</summary>
<figure class="wp-block-image size-full"><picture class="wp-picture-46" style="display: contents;"><source type="image/avif" srcset="http://localhost:8888/wp-content/uploads/2024/08/leaves-jpg.avif"></picture></figure>
</details>

### CODE REVIEW

**Comment by westonruter** [comment]
Sorry, what feedback?

**Comment by westonruter** [comment]
Oh, seems the description was accidentally copied from https://github.com/WordPress/performance/pull/1449#issuecomment-2285810613

**Comment by westonruter** [comment]
@mukeshpanchal27 Please update the PR title and description.

**Comment by mukeshpanchal27** [comment]
Closing as it's testing PR

**Pull request closed without merging**
